// This file was generated by Prisma, and assumes you have installed the following:
// prisma.config.ts
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasource: {
    url: process.env.DATABASE_URL, // ดึงค่าจาก Render Env ที่เราตั้งไว้
  },
});